spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 512KB
      max-request-size: 1MB
  main:
    allow-bean-definition-overriding: true
server:
  port: 80
mybatis-plus:
  mapper-locations: classpath:tech/spiritualdarkness/itu/dao/*.xml
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    map-underscore-to-camel-case: false
    lazy-loading-enabled: true
pic:
  dir: D:\QingQingStudio\IndieForum\Backend\IndieForumBackend\pic